-- messages 테이블 구조 확인

-- 1. 테이블 존재 여부 확인
SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_name = 'messages'
) as table_exists;

-- 2. messages 테이블의 모든 컬럼 확인
SELECT 
    column_name,
    data_type,
    character_maximum_length,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'public' 
AND table_name = 'messages'
ORDER BY ordinal_position;

-- 3. 테이블이 없다면 생성
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,  -- 또는 message TEXT NOT NULL
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ip_hash VARCHAR(64)
);

-- 4. 기존 테이블의 샘플 데이터 확인 (구조 파악용)
SELECT * FROM messages LIMIT 1;