-- 가격 기록 테이블 생성
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    high_price DECIMAL(20, 2) NOT NULL,
    low_price DECIMAL(20, 2) NOT NULL,
    close_price DECIMAL(20, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(symbol, date)
);

-- 인덱스 생성 (검색 성능 향상)
CREATE INDEX idx_price_history_symbol ON price_history(symbol);
CREATE INDEX idx_price_history_date ON price_history(date DESC);
CREATE INDEX idx_price_history_symbol_date ON price_history(symbol, date DESC);

-- RLS 정책 설정
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 읽기 가능
CREATE POLICY "Enable read access for all users" ON price_history
    FOR SELECT 
    USING (true);

-- 인증된 사용자만 추가 가능
CREATE POLICY "Enable insert for authenticated users" ON price_history
    FOR INSERT 
    TO authenticated
    WITH CHECK (true);

-- 인증된 사용자만 수정 가능
CREATE POLICY "Enable update for authenticated users" ON price_history
    FOR UPDATE 
    TO authenticated
    USING (true);

-- 샘플 데이터 (선택사항 - 테스트용)
-- INSERT INTO price_history (symbol, date, high_price, low_price, close_price) VALUES
-- ('BTCUSDT', CURRENT_DATE - INTERVAL '1 day', 95000.00, 92000.00, 94500.00),
-- ('BTCUSDT', CURRENT_DATE - INTERVAL '2 days', 94000.00, 91000.00, 93000.00),
-- ('ETHUSDT', CURRENT_DATE - INTERVAL '1 day', 3500.00, 3300.00, 3450.00),
-- ('ETHUSDT', CURRENT_DATE - INTERVAL '2 days', 3400.00, 3200.00, 3350.00);