-- 완전한 채팅 리셋 및 수정

-- 1. 기존 테이블 백업 (데이터가 있다면)
CREATE TABLE IF NOT EXISTS messages_backup AS SELECT * FROM messages;

-- 2. 기존 테이블 삭제
DROP TABLE IF EXISTS messages CASCADE;

-- 3. 새로운 테이블 생성 (간단하게)
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    browser_id VARCHAR(100),
    ip_hash VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 인덱스
CREATE INDEX idx_messages_created ON messages(created_at DESC);

-- 5. RLS 비활성화 (먼저 테스트)
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;

-- 6. 테스트 데이터
INSERT INTO messages (message, browser_id) VALUES 
('채팅 시스템 재설정 완료!', 'system'),
('이제 메시지를 보낼 수 있습니다.', 'system');

-- 7. 확인
SELECT * FROM messages ORDER BY created_at DESC;

-- 8. 성공하면 RLS 활성화
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 9. 모든 사용자 허용 정책
CREATE POLICY "Anyone can do anything" ON messages
    FOR ALL 
    USING (true)
    WITH CHECK (true);

-- 10. 다시 테스트
INSERT INTO messages (message) VALUES ('RLS 활성화 후 테스트');

-- 11. 최종 확인
SELECT COUNT(*) as total, MAX(created_at) as latest FROM messages;