-- messages 테이블 완전 재설정 (최종 수정)

-- 1. 기존 테이블 삭제하고 새로 생성 (깔끔하게 시작)
DROP TABLE IF EXISTS messages CASCADE;

-- 2. 새 테이블 생성
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. RLS 비활성화 (먼저 테스트)
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;

-- 4. 테스트 메시지 삽입
INSERT INTO messages (message) VALUES 
    ('채팅 시스템이 작동합니다! 🎉'),
    ('테스트 메시지입니다.'),
    ('안녕하세요!');

-- 5. 확인
SELECT * FROM messages ORDER BY created_at DESC;

-- 6. RLS 활성화 및 정책 설정 (작동 확인 후)
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 읽고 쓸 수 있도록 설정
CREATE POLICY "Enable all for everyone" ON messages
    FOR ALL 
    USING (true)
    WITH CHECK (true);

-- 7. 다시 테스트
INSERT INTO messages (message) VALUES ('RLS 활성화 후 테스트');

-- 8. 최종 확인
SELECT COUNT(*) as total_messages FROM messages;