name: Daily Crypto Price Collector

on:
  schedule:
    # 매일 UTC 00:01 (한국시간 오전 9:01)에 실행
    - cron: '1 0 * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  collect-prices:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install firebase-admin
        npm install node-fetch
    
    - name: Collect and save prices
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        node collect-daily-prices.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update crypto prices $(date +'%Y-%m-%d')" && git push)